config/routes.rb
Rails.application.routes.draw do

  get 'passwords/edit'
  get 'accounts/show'
  get 'accounts/edit'

  root 'budgets#top'
  

  resources :users, only: [:new, :create, :destroy] do
    resources :budgets, except: [:edit, :update] do
      collection do
        get :graph
      end
    end
  end

  namespace :admin do
    root 'users#top'
    resources :users do
      resources :budgets, except: [:edit, :update] do
        collection do
          get :graph
        end
      end
    end
  end

  resource :session, only: [:create, :destroy]
  resource :account, only: [:show, :edit, :update]
  resource :password, only: [:show, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_admin_menu.html.slim
ul.global-nav
  li.nav-item = active_link_to "トップ", :root, active: :exclusive
  li.nav-item = active_link_to "ユーザー一覧", admin_users_path
  li.nav-item = active_link_to "収支", user_budgets_path(current_user), active: :exclusive
  li.nav-item = active_link_to "グラフ", "#{user_budgets_path(current_user)}/graph", active: :exclusive

app/views/shared/_error_message.html.slim
- if model.errors.any?
  .alert
    ul
      - model.errors.full_messages.each do |message|
        li = message

app/views/shared/_form.html.slim
.form_wrapper
    h1.form-title = title
    .form_group
      .form_label
        = f.label :name
      .form_field
        = f.text_field :name, autofocus: true, size: "60px"

    .form_group
      .form_label
        = f.label :email
      .form_field
        = f.text_field :email, size: "60px"

    / 新規登録時のみパスワードフォームを表示
    - if controller.action_name != "edit"
      .form_group
        .form_label
          = f.label :password
        .form_field
          = f.password_field :password, size: "60px"

      .form_group
        .form_label
          = f.label :password_confirmation
        .form_field
          = f.password_field :password_confirmation, size: "60px"

    / アカウントページから変更できなくする
    - if controller.kind_of?(Admin::UsersController) && current_user&.administrator?
        .form_group
          .form_label
            = f.label :administrator
          .form_field
            = f.check_box :administrator, disabled: !current_user.administrator?
    
    .form_group
      = f.submit

app/views/shared/_header.html.slim
- if current_user.administrator
  == render "shared/admin_menu"
- else
  == render "shared/menu"

- if current_user
  ul.account_menu
    = link_to "#{current_user.name}さん", :account
    = link_to "ログアウト", :session, method: :delete, data: { confirm: "ログアウトしますか？" }

app/views/shared/_login_form.html.slim
- if flash.alert
  p.alert = flash.alert

h2.login_title ログイン

.login_form
  = form_with url: :session, id: "login_form", local: true do |f|

    .form
      = f.label :name
      = f.text_field :name

    .form
      = f.label :password
      = f.password_field :password

    = f.submit "ログイン"

app/views/shared/_menu.html.slim
ul.global-nav
  li.nav-item = active_link_to "トップ", :root, active: :exclusive
  li.nav-item = active_link_to "収支", user_budgets_path(current_user), active: :exclusive
  li.nav-item = active_link_to "グラフ", "#{user_budgets_path(current_user)}/graph"

app/views/shared/_sidebar.html.slim
== render "shared/login_form" unless current_user