config/routes.rb
Rails.application.routes.draw do

  get 'passwords/edit'
  get 'accounts/show'
  get 'accounts/edit'

  root 'budgets#top'
  

  resources :users, only: [:new, :create, :destroy] do
    resources :budgets, except: [:edit, :update] do
      collection do
        get :graph
      end
    end
  end

  namespace :admin do
    root 'users#top'
    resources :users do
      resources :budgets, except: [:edit, :update] do
        collection do
          get :graph
        end
      end
    end
  end

  resource :session, only: [:create, :destroy]
  resource :account, only: [:show, :edit, :update]
  resource :password, only: [:show, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :budgets, dependent: :destroy

    validates :name, presence: true, uniqueness: true, length: { maximum: 20 }
    validates :email, presence: true, email: true, uniqueness: true

    attr_accessor :current_password
    validates :password, presence: { if: :current_password }
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::Base
  before_action :login_required, except: [:new, :create]

  def top
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to [:admin, @user], notice: "ユーザー登録しました"
    else
      render "new"
    end
  end

  def update
    @user = User.find(params[:id])
    @user.assign_attributes(user_params)
    if @user.save
      redirect_to [:admin, @user], notice: "ユーザー情報を更新しました"
    else
      render "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to :root, notice: "ユーザーを削除しました"
  end

  private def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation,
      :administrator
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_required, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save

      # 登録出来たらメールを送信
      UserMailer.with(user: @user).signup_email.deliver_later
      redirect_to @user, notice: "ユーザー登録しました" if current_user
      # 新規登録後にログインしてトップページへリダイレクト
      session[:user_id] = @user.id
      redirect_to :root, notice: "ユーザー登録しました"
    
    else
      render "new"
    end
  end


  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to :root, notice: "ユーザーを削除しました"
  end

  private def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation,
      :administrator
    )
  end
end

app/helpers/admin/user_helper.rb
module Admin::UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_body.html.slim
.user_name
  = "名前："
  = @user.name
.user_email
  = "メールアドレス："
  = @user.email

= link_to 'ユーザ削除', [:admin, @user], method: :delete, data: { confirm: "本当に削除しますか？" }

app/views/admin/users/edit.html.slim
p = link_to "ユーザー詳細に戻る", admin_user_path(@user)

= form_with model: [:admin, @user], scope: :user, local: true do |f|
  == render "shared/form", f: f

app/views/admin/users/index.html.slim
h2.table_title ユーザー一覧

table.list
  thead
    tr
      th 名前
      th メールアドレス
  tbody
    - @users.each do |user|
      tr
        td = link_to user.name, admin_user_path(user)
        td = user.email

= link_to '新規ユーザ登録', new_admin_user_path, class: 'btn btn-primary'

app/views/admin/users/new.html.slim
- if current_user
  = link_to 'ユーザ一覧へ戻る', admin_users_path
- else
  h1 ユーザの新規登録

= form_with model: [:admin, @user], scope: :user, local: true do |f|
  == render "shared/form", f: f

app/views/admin/users/show.html.slim
h2 ユーザー詳細

p = link_to "ユーザー一覧に戻る", admin_users_path
p = link_to "ユーザー情報の編集", edit_admin_user_path

== render "body"

app/views/admin/users/top.html.slim
h1 Admin::User#top
p Find me in app/views/admin/user/top.html.slim